// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace _60322_1_Lagutin.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Nick : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Nick));
        
        string IMigrationMetadata.Id
        {
            get { return "201711291504435_Nick"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
